### ISSUE TITLE
Error since Update 

### ISSUE THREAD

**Issue by 00Twister00** [SAIC-iSmart-API/saic-home-assistant-addon#104]
hey i get this Error after Update Homeassistant 

ValueError: non-hexadecimal number found in fromhex() arg at position 4
2024-08-09 11:06:24,241 [  INFO  ] Connected to MQTT broker - mqtt_publisher
2024-08-09 11:06:24,258 [  INFO  ] Scheduler started - apscheduler.scheduler
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 712, in <module>
    asyncio.run(mqtt_gateway.run(), debug=debug_log_enabled())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/app/./mqtt_gateway.py", line 301, in run
    login_response_message = self.saic_api.login()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 119, in login
    self.message_v1_1_coder.decode_response(login_response_hex, login_response_message)
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/ota_v1_1/Message.py", line 13, in decode_response
    super().decode_response(message, decoded_message)
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/common_model.py", line 401, in decode_response
    buffered_message_bytes = io.BytesIO(bytes.fromhex(message[5:]))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by dbrnz** [comment]
Ditto...

**Comment by dbrnz** [comment]
Is this not the same as #51?

**Comment by 00Twister00** [comment]
I use the Pre-Version now ... Works fine
