### ISSUE TITLE
 MPDispatcherBody.uid: out of data (At bit offset: 58)

### ISSUE THREAD

**Issue by jomach** [SAIC-iSmart-API/saic-home-assistant-addon#35]
Hello, after installing and connecting to mqtt broker I get: 

2023-10-05 11:49:52,030 Connected to MQTT broker
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 589, in <module>
    mqtt_gateway.run()
  File "/usr/src/app/./mqtt_gateway.py", line 269, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 120, in login
    self.message_v1_1_coder.decode_response(login_response_hex, login_response_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/ota_v1_1/Message.py", line 13, in decode_response
    super().decode_response(message, decoded_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/common_model.py", line 400, in decode_response
    message_body_dict = self.asn1_tool_uper.decode(message_body.asn_type, dispatcher_message_bytes)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/compiler.py", line 167, in decode
    decoded = type_.decode(data)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 500, in decode
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 496, in decode
    return self._type.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 830, in decode
    decoded = self.decode_root(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 848, in decode_root
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 844, in decode_root
    value = member.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 107, in decode
    value = decoder.read_non_negative_binary_integer(self.bits_per_character)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 449, in read_non_negative_binary_integer
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: MPDispatcherBody.uid: out of data (At bit offset: 58)

**Comment by Tonno87** [comment]
Seems fixed :)
