### ISSUE TITLE
SAIC Login Fails when starting

### ISSUE THREAD

**Issue by N0thingSpecial** [SAIC-iSmart-API/saic-home-assistant-addon#53]
When I start SAIC MQTT Gateway (Python), I instantly get a crash:

2024-01-28 20:56:31,313 [  INFO  ] Connected to MQTT broker - mqtt_publisher
2024-01-28 20:56:31,326 [  INFO  ] Scheduler started - apscheduler.scheduler
2024-01-28 20:56:31,646 [ ERROR  ] MqttGateway crashed due to SaicApiException - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 301, in run
    login_response_message = self.saic_api.login()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 122, in login
    raise SaicApiException(login_response_message.body.error_message,
saic_ismart_client.exceptions.SaicApiException: return code: 15033, message: Sorry, the account has been locked, please try again tomorrow or you may reset password by clicking “forget password”if you forget it.
return code: 15033, message: Sorry, the account has been locked, please try again tomorrow or you may reset password by clicking “forget password”if you forget it.

I tried the image "saicismartapi/saic-python-mqtt-gateway:latest" on another computer. It worked. But when starting this add-on with home-assistant it always brings up this error. I already double checked the login. I changed my password multiple times cause some people said regex would filter passwords. What am I missing?

**Comment by Tonno87** [comment]
Update to 0.5.1 is out now. Hope this helps.

**Comment by N0thingSpecial** [comment]
It's working now. Thank you so much for your work!

**Comment by mkrus** [comment]
updated to latest now, and getting: 
`2024-01-28 22:28:11,502 [ ERROR  ] API call return code is not acceptable: 1000020: {"code":1000020,"message":"The country code not exist !"}. Headers: Headers({'date': 'Sun, 28 Jan 2024 22:28:11 GMT', 'content-type': 'application/x-www-form-urlencoded', 'content-length': '57', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1706480891484', 'app-verification-string': '8457f02be8da897796942f487a8ff12de0d8ac2efbca15f6934b02c648541ffc'}) - saic_ismart_client_ng.api.base
`

**Comment by Tonno87** [comment]
Try to change the SAIC_URI to: https://gateway-mg-eu.soimt.com/api.app/v1/

**Comment by flaparoo** [comment]
The new version doesn't seem to work for Australian users. With v0.5.1 and my best guess for the Australian URL (`https://gateway-mg-au.soimt.com/api.app/v1/`), I get a `The account is not registered.` error:
```
2024-01-29 10:20:46,189 [ ERROR  ] API call return code is not acceptable: 1000036: {"code":1000036,"message":"The account is not registered."}. Headers: Headers({'date': 'Mon, 29 Jan 2024 02:20:46 GMT', 'content-type': 'application/x-www-form-urlencoded', 'content-length': '59', 'connection': 'keep-alive', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'DENY', 'app-content-encrypted': '1', 'original-content-type': 'application/x-www-form-urlencoded', 'app-send-date': '1706494846080', 'app-verification-string': '91b47579deef3e40709b5883a6d6bccd51ac797ff9045171bbd9805f4ad6be7c'}) - saic_ismart_client_ng.api.base
```
The SAIC MQTT Python gateway works fine with v0.4.6 (using SAIC_URL `https://tap-au.soimt.com`).

**Comment by Tonno87** [comment]
I can create a legacy addon after work, please be patient.

**Comment by flaparoo** [comment]
Thanks - and no rush.
Rolling back to v0.4.6 keeps it working for now.

**Comment by Tonno87** [comment]
You can install the legacy addon now with 0.4.6:
![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/05e4732d-100a-458a-a23d-ad1152e84b1b)

Hope this helps :)

**Comment by mkrus** [comment]
do we need to uninstall the old one? What will happen to entity ids?

**Comment by Tonno87** [comment]
The new add-on is identical to the 0.4.6 gateway, only the container slug is another one.

Remove or deactivate the old gateway, install the new one and re-enter your configuration.
If you can roll back with backup, do it and copy your configuration by switching to yaml mode:
![image](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/f4dd0182-9621-459c-871c-fa3899f70810)

Then you can copy it to the new gateway and start it. Every entity is coded with your VIN, so it should work!

**Comment by mkrus** [comment]
thanks for your help! Will try it out.

No hurry for me though, I hit a deer and the MG4 is in the garage for the foreseeable future :(

**Comment by Tonno87** [comment]
Yes, we need to find out all other Uri's to connect to the servers, the default Uri is for european users only.

**Comment by pmannk** [comment]
Thanks for this! Confirming it works OK for me too (AU, MG4)

**Comment by Tonno87** [comment]
I think you have to wait for iSmart version 2.x:

![Screenshot_20240130-145254.png](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/assets/59800400/fa6bc5c6-3d19-45dd-b212-c18fb611a34a)
