### ISSUE TITLE
Error message: handle_vehicle loop failed during SAIC API call

### ISSUE THREAD

**Issue by DrKoma21** [SAIC-iSmart-API/saic-home-assistant-addon#78]
I setup the add-on for HA (stable version). After the start of the add-on I receive the following error:

2024-04-04 20:01:24,184 [ ERROR  ] handle_vehicle loop failed during SAIC API call. Waiting 30s before retrying - 

After 30s the error repeats.

I am grateful for any advice.

**Comment by nanomad** [comment]
Please share a longer log

Il Gio 4 Apr 2024, 20:08 DrKoma21 ***@***.***> ha scritto:

**Comment by DrKoma21** [comment]
Here a longer log with that error:

`2024-04-04 20:21:15,711 [ ERROR  ] handle_vehicle loop failed during SAIC API call. Waiting 30s before retrying - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 91, in handle_vehicle
    vehicle_status = await self.update_vehicle_status()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./mqtt_gateway.py", line 125, in update_vehicle_status
    vehicle_status_response = await self.saic_api.get_vehicle_status(self.vin_info.vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/__init__.py", line 15, in get_vehicle_status
    return await self.execute_api_call_with_event_id(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 124, in execute_api_call_with_event_id
    return await execute_api_call_with_event_id_inner(event_id='0')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 115, in execute_api_call_with_event_id_inner
    return await self.execute_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 92, in execute_api_call
    return await self.deserialize(req, response, out_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 185, in deserialize
    raise se
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 154, in deserialize
    raise SaicApiRetryException(error_message, event_id=event_id, return_code=return_code)
saic_ismart_client_ng.exceptions.SaicApiRetryException: return code: 4, message: The remote control instruction failed, please try again later., event_id: 1003541603`

**Comment by nanomad** [comment]
This is unfortunately an expected error. As soon as you drive the car a bit
and assuming it has cellular reception it will get unstuck

Il Gio 4 Apr 2024, 20:23 DrKoma21 ***@***.***> ha scritto:

**Comment by DrKoma21** [comment]
Thank you for your quick answer. Do you know if it is possible to check cellular reception in the car? Is there a way?

**Comment by nanomad** [comment]
I'm assuming you don't know the internal esim number. I guess the only way
is to get in the car and check the signal reception icon in the top right
corner of the display once it starts up.


Keep in mind the car has some automatic "power saving" features where it
may disable the telematics box to save power.

Il Gio 4 Apr 2024, 20:32 DrKoma21 ***@***.***> ha scritto:
