### ISSUE TITLE
Error since home assistant update

### ISSUE THREAD

**Issue by merlin-marvin** [SAIC-iSmart-API/saic-home-assistant-addon#99]
Hello

Since HA update today, all sensor of my MG4 appears unaivalables.

SAIC MQTT Gateway (Python) (PreRelease)
Current version: 0.6.2

Home Assistant
    Core 2024.6.2
    Supervisor 2024.06.0
    Operating System 12.3 

Error in addon logs:
2024-06-11 20:02:25,792 [ ERROR  ] handle_vehicle loop failed with an unexpected exception - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 96, in handle_vehicle
    vehicle_status = await self.update_vehicle_status()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./mqtt_gateway.py", line 146, in update_vehicle_status
    self.vehicle_state.handle_vehicle_status(vehicle_status_response)
  File "/usr/src/app/vehicle.py", line 209, in handle_vehicle_status
    raise MqttGatewayException(
exceptions.MqttGatewayException: Vehicle status time drifted too much from current time: 4969 days, 9:11:41.208273
2024-06-11 20:02:55,870 [  INFO  ] Updating vehicle status - __main__

Thanks

**Comment by nanomad** [comment]
Hi,

This happens from time to time as MG servers provide weird data (In your
case data that's time stamped in the future....). Usually it's enough to
drive the car a bit and potentially restart the add-on



Il Mar 11 Giu 2024, 20:10 merlin-marvin ***@***.***> ha
scritto:

**Comment by merlin-marvin** [comment]
thank you for your reply. Indeed it is restored at this moment.
